name: Feature request
description: Suggest an idea for this project
title: "✨ [Feature Request]: "
labels: ["enhancement"]
assignees: 
  - Kolozuz

body:
  - type: textarea
    id: desc
    attributes:
      label: "Description"
      description: Describe what you would like as a new feature, and the reason for it
      value: |
        I want you to add ponies that fly across the page...
        Because ponies are cool...
    validations:
      required: true
- type: markdown
    attributes:
      value: |
        <!-- You don't need to delete the comments -->
        <!-- These comments are only visible when writing the issue -->
        ## Acceptance Criteria <!-- Complete list of explicitly required items for the development to be accepted and implemented -->
        
        - [ ] 
        - [ ] 
        
        
        ### Current 
        <!-- If it exists. The solution implemented at the time of writing the issue, why it should change or why it does not meet the requirements -->
        
        
        ### Possible Solutions 
        <!-- Suggestions can come from the developer who assigned the issue or the assigned developer -->
        
        
        ### Additional Context / Notes 
        <!-- Information that is tangentially or indirectly related to the issue, add any other context or screenshots about the feature request here.-->
