name: Feature request
about: Suggest an idea for this project
title: "✨ [Feature Request]: "
labels: ["feature", "enhancement"]
assignees: 
  - Kolozuz

- type: markdown
    attributes:
      value: |
        <!-- You don't need to delete the comments -->
        <!-- These comments are only visible when writing the issue -->
        # Description <!-- Details of the current situation and the expected outcome -->
        
        ## Acceptance Criteria <!-- Complete list of explicitly required items for the development to be accepted and implemented -->
        
        - [ ] 
        - [ ] 
        
        
        ### Current 
        <!-- If it exists. The solution implemented at the time of writing the issue, why it should change or why it does not meet the requirements -->
        
        
        ### Possible Solutions 
        <!-- Suggestions can come from the developer who assigned the issue or the assigned developer -->
        
        
        ### Additional Context / Notes 
        <!-- Information that is tangentially or indirectly related to the issue, add any other context or screenshots about the feature request here.-->
